include: ../../analysis_options.yaml

analyzer:
  exclude:
    - 'example/**'

linter:
  rules:
    - avoid-shadowing: false

dart_code_metrics:
  rules:
    - parameters-ordering: false
    - avoid-flexible-outside-flex: false
    - format-comment:
        only-doc-comments: true
    - avoid-dynamic: false
    - avoid-empty-setstate: false
    - avoid-long-files: false
    - avoid-missed-calls: false
    - avoid-nullable-interpolation: false
    - avoid-shadowing: false
    - avoid-throw-in-catch-block: false
    - avoid-unsafe-collection-methods: false
    - avoid-unused-parameters: false
    - dispose-fields: false
    - move-variable-closer-to-its-usage: false
    - no-empty-block: false
    - prefer-boolean-prefixes: false
    - prefer-correct-callback-field-name: false
    - prefer-correct-identifier-length: false
    - prefer-single-widget-per-file: false
    - avoid-returning-widgets: false
    - prefer-static-class: false
    - no-magic-string: false
