name: coui_web
description: A type-safe Dart implementation of DaisyUI components for Jaspr, providing a fluent API for building beautiful web apps (PoC)
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  jaspr: ^0.21.1
  universal_web: ^1.1.1

dev_dependencies:
  build_runner: ^2.7.0
  dart_code_metrics_presets: ^2.25.1
  jaspr_builder: ^0.21.2
  jaspr_lints: ^0.5.1
  jaspr_web_compilers: ^4.2.3+1
  very_good_analysis: ^10.0.0

# topics:
#   - jaspr
#   - daisyui
#   - ui-components
#   - web