name: coui_mcp
description: MCP server for CoUI Flutter component documentation
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
