import 'package:coui_web/coui_web.dart';
// Generated by Jaspr.
import 'package:example/jaspr_options.dart';
import 'package:jaspr/server.dart';

void main() {
  Jaspr.initializeApp(options: defaultJasprOptions);

  runApp(
    Document(
      body: const CoUIShowcase(),
      head: [
        link(href: 'styles.css', rel: 'stylesheet'),
        meta(
          content: 'width=device-width, initial-scale=1',
          name: 'viewport',
        ),
      ],
      title: 'CoUI Example - Component Showcase',
    ),
  );
}

class CoUIShowcase extends StatelessComponent {
  const CoUIShowcase({super.key});

  @override
  Component build(BuildContext context) {
    return div(
      [
        // Header
        div(
          [
            h1(
              [text('🎨 CoUI Component Showcase')],
              classes: 'text-4xl font-bold text-center mb-2',
            ),
            p(
              [text('Type-safe DaisyUI components for Jaspr')],
              classes: 'text-center text-base-content/70 mb-12',
            ),

            // Alert Examples
            _buildSection(
              content: [
                Alert(
                  [text('🎉 Welcome to CoUI! This is a success message.')],
                  style: const [Alert.success],
                ),
                Alert(
                  [text('⚠️ Please check your input. This is a warning.')],
                  style: const [Alert.warning],
                ),
                Alert(
                  [text('❌ Something went wrong. This is an error message.')],
                  style: const [Alert.error],
                ),
                Alert(
                  [text("ℹ️ Here's some helpful information for you.")],
                  style: const [Alert.info],
                ),
              ],
              description: 'User notifications and feedback messages',
              title: 'Alert Components',
            ),

            // Button Examples
            _buildSection(
              content: [
                div(
                  [
                    Button(
                      style: const [Button.primaryStyle],
                      child: text('Primary'),
                    ),
                    Button(
                      style: const [Button.secondaryStyle],
                      child: text('Secondary'),
                    ),
                    Button(
                      style: const [Button.accentStyle],
                      child: text('Accent'),
                    ),
                    Button(
                      style: const [Button.outlineStyle],
                      child: text('Outline'),
                    ),
                    Button(
                      style: const [Button.ghostStyle],
                      child: text('Ghost'),
                    ),
                  ],
                  classes: 'flex flex-wrap gap-2',
                ),
              ],
              description: 'Interactive elements with various styles',
              title: 'Button Components',
            ),

            // Input Examples
            _buildSection(
              content: [
                div(
                  [
                    Input(
                      placeholder: 'Enter your email',
                      style: const [Input.primary],
                      type: 'email',
                    ),
                    Input(
                      placeholder: 'Enter password',
                      style: const [Input.bordered],
                      type: 'password',
                    ),
                  ],
                  classes: 'space-y-4',
                ),
              ],
              description: 'Form inputs with validation',
              title: 'Input Components',
            ),

            // Badge Examples
            _buildSection(
              content: [
                div(
                  [
                    Badge([text('Primary')], style: const [Badge.primary]),
                    Badge([text('Secondary')], style: const [Badge.secondary]),
                    Badge([text('Accent')], style: const [Badge.accent]),
                    Badge([text('Success')], style: const [Badge.success]),
                    Badge([text('Error')], style: const [Badge.error]),
                  ],
                  classes: 'flex flex-wrap gap-2',
                ),
              ],
              description: 'Status indicators and labels',
              title: 'Badge Components',
            ),

            // Footer
            div(
              [
                p(
                  [
                    text('Built with ❤️ using CoUI • '),
                    a(
                      [text('View on GitHub')],
                      classes: 'link link-primary',
                      href: 'https://github.com/PhilippHGerber/ui_components',
                    ),
                  ],
                  classes: 'text-base-content/60',
                ),
              ],
              classes: 'text-center mt-16 pt-8 border-t border-base-300',
            ),
          ],
          classes: 'max-w-6xl mx-auto',
        ),
      ],
      classes: 'min-h-screen bg-base-100 p-8',
    );
  }

  static Component _buildSection({
    required List<Component> content,
    required String description,
    required String title,
  }) {
    return div(
      [
        div(
          [
            h2([text(title)], classes: 'text-2xl font-bold mb-2'),
            p([text(description)], classes: 'text-base-content/70'),
          ],
          classes: 'mb-8',
        ),
        div(content, classes: 'space-y-6'),
      ],
      classes: 'mb-16',
    );
  }
}
