import 'package:coui_web/coui_web.dart';
// Generated by Jaspr
import 'package:example/jaspr_options.dart';
import 'package:jaspr/server.dart';

void main() {
  Jaspr.initializeApp(options: defaultJasprOptions);

  runApp(
    Document(
      body: const CoUIShowcase(),
      head: [
        link(href: 'styles.css', rel: 'stylesheet'),
        meta(content: 'width=device-width, initial-scale=1', name: 'viewport'),
      ],
      title: 'CoUI Example - Component Showcase',
    ),
  );
}

class CoUIShowcase extends StatelessComponent {
  const CoUIShowcase({super.key});

  @override
  Component build(BuildContext context) {
    return div(
      [
        // Header
        div(
          [
            h1(
              [text('🎨 CoUI Component Showcase')],
              classes: 'text-4xl font-bold text-center mb-2',
            ),
            p(
              [text('Type-safe DaisyUI components for Jaspr')],
              classes: 'text-center text-base-content/70 mb-12',
            ),

            // Alert Examples
            _buildSection(
              content: [
                Alert(
                  [text('🎉 Welcome to CoUI! This is a success message.')],
                  style: const [Alert.success],
                ),

                Alert(
                  [text('⚠️ Please check your input. This is a warning.')],
                  style: const [Alert.warning],
                ),

                Alert(
                  [text('❌ Something went wrong. This is an error message.')],
                  style: const [Alert.error],
                ),

                Alert(
                  [text("ℹ️ Here's some helpful information for you.")],
                  style: const [Alert.info],
                ),

                // Outlined style
                Alert(
                  [text('🔄 Processing your request... (outlined style)')],
                  style: const [Alert.info, Alert.outline],
                ),
              ],
              description: 'User notifications and feedback messages',
              title: 'Alert Components',
            ),

            // Card Examples
            _buildSection(
              content: [
                div(
                  [
                    // Basic card
                    Card(
                      [
                        CardBody([
                          CardTitle([text('Basic Card')]),
                          p([
                            text(
                              'This is a simple card with some content inside.',
                            ),
                          ]),
                          CardActions([
                            Button(
                              [text('Action')],
                              style: const [Button.primary, Button.sm],
                            ),
                          ]),
                        ]),
                      ],
                      style: const [BgUtil.base300, Effects.shadowLg],
                    ),

                    // Card with image
                    Card(
                      [
                        Figure([
                          img(
                            alt: 'Random image',
                            src: 'https://picsum.photos/400/200?random=1',
                          ),
                        ]),
                        CardBody([
                          CardTitle([
                            text('Image Card'),
                            Badge(
                              [text('NEW')],
                              style: const [Badge.secondary],
                            ),
                          ]),
                          p([text('Card with a beautiful image and badge.')]),
                          CardActions([
                            Button([text('View')], style: const [Button.ghost]),
                            Button(
                              [text('Buy Now')],
                              style: const [Button.primary],
                            ),
                          ]),
                        ]),
                      ],
                      style: const [BgUtil.base300, Effects.shadowLg],
                    ),

                    // Compact card
                    Card(
                      [
                        CardBody([
                          CardTitle([text('Compact Card')]),
                          p([text('Smaller card perfect for dashboards.')]),
                        ]),
                      ],
                      style: const [Card.border, Effects.shadowLg, Card.xs],
                    ),
                  ],
                  classes:
                      'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
                ),
              ],
              description: 'Content containers and layout blocks',
              title: 'Card Components',
            ),

            // Button Examples
            _buildSection(
              content: [
                // Color variants
                div(
                  [
                    Button([text('Neutral')], style: const [Button.neutral]),
                    Button([text('Primary')], style: const [Button.primary]),
                    Button(
                      [text('Secondary')],
                      style: const [Button.secondary],
                    ),
                    Button([text('Accent')], style: const [Button.accent]),
                    Button([text('Info')], style: const [Button.info]),
                    Button([text('Success')], style: const [Button.success]),
                    Button([text('Warning')], style: const [Button.warning]),
                    Button([text('Error')], style: const [Button.error]),
                  ],
                  classes: 'flex flex-wrap gap-2 mb-4',
                ),

                // Style variants
                div(
                  [
                    Button([text('Outline')], style: const [Button.outline]),
                    Button([text('Ghost')], style: const [Button.ghost]),
                    Button([text('Link')], style: const [Button.link]),
                    Button([text('Soft')], style: const [Button.soft]),
                    Button([text('Dash')], style: const [Button.dash]),
                  ],
                  classes: 'flex flex-wrap gap-2 mb-4',
                ),

                // Size variants
                div(
                  [
                    Button([text('XS')], style: const [Button.xs]),
                    Button([text('SM')], style: const [Button.sm]),
                    Button([text('MD')], style: const [Button.md]),
                    Button([text('LG')], style: const [Button.lg]),
                    Button([text('XL')], style: const [Button.xl]),
                  ],
                  classes: 'flex flex-wrap items-center gap-2 mb-4',
                ),

                // Shape variants
                div(
                  [
                    Button([text('Wide Button')], style: const [Button.wide]),
                    Button([text('⭐')], style: const [Button.square]),
                    Button([text('💝')], style: const [Button.circle]),
                    Button([text('Block Button')], style: const [Button.block]),
                  ],
                  classes: 'flex flex-wrap items-center gap-2',
                ),
              ],
              description:
                  'Interactive elements with various styles and states',
              title: 'Button Components',
            ),

            // Input Examples
            _buildSection(
              content: [
                div(
                  [
                    // Basic inputs
                    div([
                      label(
                        [text('Email Address')],
                        classes: 'block text-sm font-medium mb-2',
                      ),
                      const Input(
                        placeholder: 'Enter your email',
                        style: [Input.primary],
                        type: 'email',
                      ),
                    ]),

                    div([
                      label(
                        [text('Password')],
                        classes: 'block text-sm font-medium mb-2',
                      ),
                      const Input(
                        placeholder: 'Enter password',
                        style: [Input.secondary],
                        type: 'password',
                      ),
                    ]),

                    // Different sizes
                    div([
                      label(
                        [text('Small Input')],
                        classes: 'block text-sm font-medium mb-2',
                      ),
                      const Input(placeholder: 'Small size', style: [Input.sm]),
                    ]),

                    div([
                      label(
                        [text('Large Input')],
                        classes: 'block text-sm font-medium mb-2',
                      ),
                      const Input(placeholder: 'Large size', style: [Input.lg]),
                    ]),

                    // Validation states
                    div([
                      label(
                        [text('Success State')],
                        classes: 'block text-sm font-medium mb-2',
                      ),
                      const Input(
                        placeholder: 'Valid input',
                        style: [Input.success],
                      ),
                    ]),

                    div([
                      label(
                        [text('Error State')],
                        classes: 'block text-sm font-medium mb-2',
                      ),
                      const Input(
                        placeholder: 'Invalid input',
                        style: [Input.error],
                      ),
                    ]),
                  ],
                  classes: 'grid grid-cols-1 md:grid-cols-2 gap-4',
                ),

                // Ghost style
                div(
                  [
                    label(
                      [text('Ghost Style Input')],
                      classes: 'block text-sm font-medium mb-2',
                    ),
                    const Input(
                      placeholder: 'Transparent background',
                      style: [Input.ghost, Input.lg],
                    ),
                  ],
                  classes: 'mt-4',
                ),
              ],
              description: 'Form inputs with validation and styling',
              title: 'Input Components',
            ),

            // Badge Examples
            _buildSection(
              content: [
                // Color variants
                div(
                  [
                    Badge([text('Neutral')], style: const [Badge.neutral]),
                    Badge([text('Primary')], style: const [Badge.primary]),
                    Badge([text('Secondary')], style: const [Badge.secondary]),
                    Badge([text('Accent')], style: const [Badge.accent]),
                    Badge([text('Info')], style: const [Badge.info]),
                    Badge([text('Success')], style: const [Badge.success]),
                    Badge([text('Warning')], style: const [Badge.warning]),
                    Badge([text('Error')], style: const [Badge.error]),
                  ],
                  classes: 'flex flex-wrap gap-2 mb-4',
                ),

                // Style variants
                div(
                  [
                    Badge([text('Outline')], style: const [Badge.outline]),
                    Badge([text('Ghost')], style: const [Badge.ghost]),
                    Badge([text('Soft')], style: const [Badge.soft]),
                    Badge([text('Dash')], style: const [Badge.dash]),
                  ],
                  classes: 'flex flex-wrap gap-2 mb-4',
                ),

                // Size variants
                div(
                  [
                    Badge([text('XS')], style: const [Badge.xs]),
                    Badge([text('SM')], style: const [Badge.sm]),
                    Badge([text('MD')], style: const [Badge.md]),
                    Badge([text('LG')], style: const [Badge.lg]),
                    Badge([text('XL')], style: const [Badge.xl]),
                  ],
                  classes: 'flex flex-wrap items-center gap-2 mb-4',
                ),

                // Practical examples
                div(
                  [
                    p([
                      text('Status: '),
                      Badge(
                        [text('Online')],
                        style: const [Badge.success, Badge.sm],
                      ),
                    ]),
                    p([
                      text('Notifications '),
                      Badge([text('3')], style: const [Badge.error, Badge.xs]),
                    ]),
                    p([
                      text('Version '),
                      Badge([text('v1.2.0')], style: const [Badge.ghost]),
                    ]),
                  ],
                  classes: 'space-y-2',
                ),
              ],
              description: 'Status indicators, labels, and counters',
              title: 'Badge Components',
            ),

            // Integration Examples
            _buildSection(
              content: [
                // Login card example
                div(
                  [
                    Card(
                      [
                        CardBody([
                          div(
                            [
                              CardTitle([
                                text('Login'),
                                Badge(
                                  [text('Secure')],
                                  style: const [Badge.success, Badge.sm],
                                ),
                              ]),
                            ],
                            classes: 'text-center mb-4',
                          ),
                          Alert(
                            [
                              text(
                                'Please enter your credentials to continue.',
                              ),
                            ],
                            style: const [Alert.info, Alert.soft],
                          ),
                          div(
                            [
                              const Input(
                                placeholder: 'Email address',
                                style: [Input.primary],
                                type: 'email',
                              ),
                              const Input(
                                placeholder: 'Password',
                                style: [Input.primary],
                                type: 'password',
                              ),
                            ],
                            classes: 'space-y-4 mt-4',
                          ),
                          CardActions([
                            Button(
                              [text('Cancel')],
                              style: const [Button.ghost],
                            ),
                            Button(
                              [text('Sign In')],
                              style: const [Button.primary],
                            ),
                          ]),
                        ]),
                      ],
                      style: const [Card.border, Card.lg],
                    ),
                  ],
                  classes: 'max-w-md mx-auto',
                ),
              ],
              description: 'Examples showing components working together',
              title: 'Component Integration',
            ),

            // Footer
            div(
              [
                p(
                  [
                    text('Built with ❤️ using CoUI • '),
                    a(
                      [text('View on GitHub')],
                      classes: 'link link-primary',
                      href: 'https://github.com/PhilippHGerber/ui_components',
                    ),
                  ],
                  classes: 'text-base-content/60',
                ),
              ],
              classes: 'text-center mt-16 pt-8 border-t border-base-300',
            ),
          ],
          classes: 'max-w-6xl mx-auto',
        ),
      ],
      classes: 'min-h-screen bg-base-100 p-8',
    );
  }

  static Component _buildSection({
    required List<Component> content,
    required String description,
    required String title,
  }) {
    return div(
      [
        div(
          [
            h2([text(title)], classes: 'text-2xl font-bold mb-2'),
            p([text(description)], classes: 'text-base-content/70'),
          ],
          classes: 'mb-8',
        ),
        div(content, classes: 'space-y-6'),
      ],
      classes: 'mb-16',
    );
  }
}
