name: i10n
description: "A Translation related package for Coui."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.9.0 <5.0.0"  
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: ^4.8.1
  slang_flutter: ^4.8.0

dev_dependencies:
  build_runner: ^2.7.0
  dart_code_metrics_presets: ^2.25.1
  flutter_lints: ^6.0.0
  slang_build_runner: ^4.8.0
  slang_gpt: ^0.11.0
  very_good_analysis: ^10.0.0
# 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
# 885029 MFA
