name: example
description: A new Jaspr project, CoUI example
version: 0.0.4
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  coui_web:
    path: ..
  jaspr: ^0.21.1

dev_dependencies:
  build_runner: ^2.7.0
  build_web_compilers: ^4.2.4
  dart_code_metrics_presets: ^2.25.1
  jaspr_builder: ^0.21.1
  jaspr_lints: ^0.5.1
  very_good_analysis: ^9.0.0


jaspr:
  mode: static
