include: ../../analysis_options.yaml
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"
    
dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml

  rules:
    - parameters-ordering: false
    - no-empty-block: false
    - avoid-returning-widgets: false
    - prefer-static-class: false
    - no-magic-string: false
