targets:
  $default:
    sources:
      include:
        - "pubspec.yaml"
        - $package$
        - lib/$lib$
        - lib/**.dart
    builders:
      mockito|mockBuilder:
        generate_for:
          - lib/**.dart