name: coui_widgetbook
description: CoUI(디자인 시스템)의 컴포넌트와 테마를 시연하는 Widgetbook 앱.
version: 0.1.0
publish_to: none
environment:
  sdk: ">=3.9.0 <5.0.0"
  flutter: ^3.32.0
resolution: workspace
dependencies:
  bloc: ^9.0.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  i10n: ^0.1.0
  icons_launcher: ^3.0.1
  image_cropper: ^9.1.0
  mockito: ^5.4.6
  provider: ^6.1.2
  throttling: ^2.0.1
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
dev_dependencies:
  build_runner: ^2.7.0
  change_app_package_name: ^1.5.0
  dart_code_metrics_presets: ^2.25.1
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^10.0.0
  widgetbook_generator: ^3.16.0
flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: packages/ui_kit/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: packages/ui_kit/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: packages/ui_kit/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: packages/ui_kit/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: packages/ui_kit/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: packages/ui_kit/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: packages/ui_kit/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: packages/ui_kit/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: packages/ui_kit/fonts/Pretendard-Black.ttf
          weight: 900
